apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: rabbitmq-default
      protocol: TCP
      port: 5672 # Expose RabbitMQ default port
      targetPort: 5672
    - name: rabbitmq-management
      protocol: TCP
      port: 15672 # Expose RabbitMQ management UI port
      targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
