// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"context"
)

type Querier interface {
	CountOrders(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteCustomer(ctx context.Context, customerID string) error
	DeleteOrder(ctx context.Context, orderID string) error
	DeleteOrderItem(ctx context.Context, orderItemID int64) error
	DeleteProduct(ctx context.Context, productID int64) error
	GetCustomer(ctx context.Context, customerID string) (Customer, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetOrder(ctx context.Context, orderID string) (Order, error)
	GetOrderItem(ctx context.Context, orderItemID int64) (OrderItem, error)
	GetProduct(ctx context.Context, productID int64) (Product, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
	ListOrderItems(ctx context.Context) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	TotalOrderPrice(ctx context.Context, orderID string) (int64, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateTotalPrice(ctx context.Context, arg UpdateTotalPriceParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
